### ISSUE TITLE
Possible Entity id leak in nebulous.entity.EntitySystem

### ISSUE THREAD

**Issue by zaneoblaneo** [NebulousDev/LoreEngine2D#1]
Not that important, due to the fact id is a long, but there is a possible id leak at EntitySystem.removeEntity
	add 5 entities
	Entity[] entities {Entity, Entity, Entity, Entity, Entity};
	remove entity[2]
	Entity[] entities {Entity, Entity, null, Entity, Entity}
	add another entity.
		will have index 5 not 2.
	Entity[] entities {Entity, Entity, null, Entity, Entity, Entity} which is != {Entity, Entity, Entity, Entity, Entity}

**Comment by NebulousDev** [comment]
I have fixed the issue with removing entities from the engine. It is now fully supported as expected.
I have not however, fixed the id reallocation because it is not entirely necessary. (unless you have 2.1billion entities) I may get around to implementing a different method at some point.

        public void removeEntity(long id) {
		
		for(Component c : idHash.get((Long)id).getComponents())
			componentHash.get(c.getClass()).remove(id);
		
		allEntities.remove(idHash.get(id));
		idHash.remove(id);
		
	    }
